### ISSUE TITLE
Finetuning Stops After Few Steps

### ISSUE THREAD

**Issue by syedmuhammad12** [ylacombe/finetune-hf-vits#12]
Hi,
I am trying continuously trying to train the model but every time I try after few steps it ends with an error. The image attached shows it. However, with the same configurations I trained a model before on which I am finetuning further. Kindly help me how can I resolve it please.
Thankyou so much btw, this repo is fabulous!!!

![issue-git](https://github.com/ylacombe/finetune-hf-vits/assets/59411455/71f3aed8-8a95-47bb-a607-8c3196a99e99)

**Comment by ylacombe** [comment]
Hey @syedmuhammad12, thanks for the issue! The traceback you've sent is really succinct, could you send the whole traceback ?

**Comment by syedmuhammad12** [comment]
Thanks for the early response @ylacombe , attached is the complete one but the actual issue is mentioned in the first post. The complete here ig just showing that wandb also stuck because of the above error.
![issue-git-1](https://github.com/ylacombe/finetune-hf-vits/assets/59411455/3fbb3038-c414-43aa-bf71-ffaa3c0501f0)

**Comment by ylacombe** [comment]
Are you on the last version of the repo ? If yes, try rebuilding the monotonic step [here](https://github.com/ylacombe/finetune-hf-vits?tab=readme-ov-file#1-requirements)! Might be related to that, let me know if it works

**Comment by syedmuhammad12** [comment]
Wow!!! Thanks @ylacombe , I updated it and rebuilt the monotonic and that worked!
