### ISSUE TITLE
error and keep crashing the system  gpu used NVIDIA GeForce RTX 4060 Ti  and used dataset 

### ISSUE THREAD

**Issue by atulpokharel001** [ylacombe/finetune-hf-vits#17]
dataset:  https://huggingface.co/datasets/mozilla-foundation/common_voice_11_0/viewer/nl
 
 
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
preprocess train dataset:  23%|██████████████████████████████                                                                                                    | 7991/34605 [05:37<02:19, 190.55 examples/s]Traceback (most recent call last):
  File "/home/ai001/Desktop/Texttospeach/finetune-hf-vits/env/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ai001/Desktop/Texttospeach/finetune-hf-vits/env/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/ai001/Desktop/Texttospeach/finetune-hf-vits/env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/home/ai001/Desktop/Texttospeach/finetune-hf-vits/env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by ylacombe** [comment]
Hi, unfortunately, your description is way too short.  
Could you please send a more detailed description of what you're trying to achieve, which configs you're using and a more detailed description of your bug ? Ideally with a script to reproduce

**Comment by atulpokharel001** [comment]
can you help to give the script of converting the dataset sample for creating the multi speaker  from the dataset https://huggingface.co/datasets/mozilla-foundation/common_voice_11_0/viewer/nl  for  the fine tunning(mms-tts) for(dutch)  model.

**Comment by atulpokharel001** [comment]
dutch config 
{
    "project_name": "dutch_female",
    "push_to_hub": true,
    "hub_model_id": "procit001/dutch_female",
    "report_to": ["wandb"],
    "overwrite_output_dir": true,
    "output_dir": "./tmp/vits_finetuned_dutch",
    "dataset_name": "procit001/clean_female_dutch_voice_v2", 
    "dataset_config_name": "default",    
    "audio_column_name": "audio", 
    "text_column_name":"text",
    "train_split_name": "train",
    "eval_split_name": "train",
    "override_speaker_embeddings": true,
    "speaker_id_column_name":"speaker_id",
    "full_generation_sample_text": "Laten we verder gaan. Kunt u ons uw naam vertellen?",
    "max_duration_in_seconds": 20,
    "min_duration_in_seconds": 1.0,
    "max_tokens_length": 500,
    "filter_on_speaker_id": 3,
    "model_name_or_path": "procit001/dutch_female",
    "do_train": true,
    "num_train_epochs": 200,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "per_device_train_batch_size": 16,
    "learning_rate": 2e-5,
    "adam_beta1": 0.8,
    "adam_beta2": 0.99,
    "warmup_ratio": 0.01,
    "group_by_length": false,
    "do_eval": true, 
    "eval_steps": 50,
    "per_device_eval_batch_size": 16,
    "max_eval_samples": 25, 
    "do_step_schedule_per_epoch": true,
    "weight_disc": 3,
    "weight_fmaps": 1,
    "weight_gen": 1,
    "weight_kl": 1.5,
    "weight_duration": 1,
    "weight_mel": 35,
    "fp16": true,
    "seed": 456
}
dataset: -procit001/clean_female_dutch_voice_v2
@ylacombe  thank you for support
