### ISSUE TITLE
how to finetune from facebook mms tts 

### ISSUE THREAD

**Issue by BB-Beta** [ylacombe/finetune-hf-vits#19]
I'm trying to finetune a english model from mms tts, the repo is https://huggingface.co/facebook/mms-tts-eng/tree/main, but there are no preprocessor_config.json file, in your examples, the base models are all from ylacombe space. so how could I finetune model from facebook space, because I'm also wanna finetune models for other languages. thank you.

**Comment by atulpokharel-gp** [comment]
# Load model directly
from transformers import AutoTokenizer, AutoModelForTextToWaveform

tokenizer = AutoTokenizer.from_pretrained("facebook/mms-tts-eng")
model = AutoModelForTextToWaveform.from_pretrained("facebook/mms-tts-eng")

try this and you will get the  model  and for datset use  ylacombe/english_dialects dataset for the english it have multiple voice choice

**Comment by ylacombe** [comment]
Thanks for helping here @atulpokharel-gp,
also for other languages, please refer to [this section](https://github.com/ylacombe/finetune-hf-vits?tab=readme-ov-file#2-model-selection) of the README !

**Comment by BB-Beta** [comment]
I'll try it, thanks for your help

**Comment by C0deXG** [comment]
Still in colab when i run this cell as suggated by @atulpokharel-gp :
`from transformers import AutoTokenizer, AutoModelForTextToWaveform

tokenizer = AutoTokenizer.from_pretrained("facebook/mms-tts-eng")
model = AutoModelForTextToWaveform.from_pretrained("facebook/mms-tts-eng")`


and then i run: `!accelerate launch run_vits_finetuning.py /content/finetune-hf-vits/training_config_examples/finetune_mms_kor.json`

i get this error: `OSError: facebook/mms-tts-som does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/facebook/mms-tts-som/tree/main' for available files.`

as we know TTS of mms model use uses a tokenizer to pre-process the text inputs to token ids. It doesn't need a preprocessor_config.json how can i do this my config file is:

`
{
    "project_name": "so-finetuning",
    "push_to_hub": true,
    "hub_model_id": "facebook/mms-tts-som",
    "report_to": ["wandb"],
    "overwrite_output_dir": true,
    "output_dir": "./tmp/vits_finetuned_Som",

    "dataset_name": "khederwaaOne/s",    
    "audio_column_name": "audio", 
    "text_column_name":"transcribe",
    "train_split_name": "train",
    "eval_split_name": "train",

    "full_generation_sample_text": "Labadaas qaybood oo aanu soo sheegnay haddii la falanqeeyo",
    
    "max_duration_in_seconds": 28.5,
   "min_duration_in_seconds": 2.4,

    "max_tokens_length": 300,

    "model_name_or_path": "facebook/mms-tts-som",


    "preprocessing_num_workers": 4,

    "do_train": true,
    "num_train_epochs": 30,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "per_device_train_batch_size": 4,
    "learning_rate": 2e-5,
    "adam_beta1": 0.8,
    "adam_beta2": 0.99,
    "warmup_ratio": 0.01,
    "group_by_length": false,

    "do_eval": true, 
    "eval_steps": 50,
    "per_device_eval_batch_size": 4,
    "max_eval_samples": 25, 
    "do_step_schedule_per_epoch": true,

    "weight_disc": 3,
    "weight_fmaps": 1,
    "weight_gen": 1,
    "weight_kl": 1.5,
    "weight_duration": 1,
    "weight_mel": 35,

    "fp16": true,
    "seed": 456
}
`
