### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to' when running example 

### ISSUE THREAD

**Issue by obairka** [ylacombe/finetune-hf-vits#29]
Hello!

`accelerate launch run_vits_finetuning.py ./training_config_examples/finetune_english.json`
I'm getting this error:

```
tokenization_utils_base.py", line 803, in to
    self.data = { k: v.to(device=device) for k, v in self.data.items() }
                     ^^^^
AttributeError: 'NoneType' object has no attribute 'to'
```
What could be causing this?
I use Apple M1 Pro Sonoma 14.4.1

**Comment by khof312** [comment]
Can you check this fix and see if it helps? https://github.com/ylacombe/finetune-hf-vits/issues/22

**Comment by obairka** [comment]
Thanks, that fixed the issue!
