### ISSUE TITLE
mms dont use pre_processor it uses toekizer so i how can i solve this?

### ISSUE THREAD

**Issue by C0deXG** [ylacombe/finetune-hf-vits#43]
Still in colab when i run this cell as suggated by @atulpokharel-gp :
`from transformers import AutoTokenizer, AutoModelForTextToWaveform

tokenizer = AutoTokenizer.from_pretrained("facebook/mms-tts-eng")
model = AutoModelForTextToWaveform.from_pretrained("facebook/mms-tts-eng")`

and then i run: !accelerate launch run_vits_finetuning.py /content/finetune-hf-vits/training_config_examples/finetune_mms_kor.json

i get this error: OSError: facebook/mms-tts-som does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/facebook/mms-tts-som/tree/main' for available files.

as we know TTS of mms model use uses a tokenizer to pre-process the text inputs to token ids. It doesn't need a preprocessor_config.json how can i do this my config file is:

`
{
"project_name": "so-finetuning",
"push_to_hub": true,
"hub_model_id": "facebook/mms-tts-som",
"report_to": ["wandb"],
"overwrite_output_dir": true,
"output_dir": "./tmp/vits_finetuned_Som",

"dataset_name": "khederwaaOne/s",    
"audio_column_name": "audio", 
"text_column_name":"transcribe",
"train_split_name": "train",
"eval_split_name": "train",

"full_generation_sample_text": "Labadaas qaybood oo aanu soo sheegnay haddii la falanqeeyo",

"max_duration_in_seconds": 28.5,
"min_duration_in_seconds": 2.4,

"max_tokens_length": 300,

"model_name_or_path": "facebook/mms-tts-som",

"preprocessing_num_workers": 4,

"do_train": true,
"num_train_epochs": 30,
"gradient_accumulation_steps": 1,
"gradient_checkpointing": false,
"per_device_train_batch_size": 4,
"learning_rate": 2e-5,
"adam_beta1": 0.8,
"adam_beta2": 0.99,
"warmup_ratio": 0.01,
"group_by_length": false,

"do_eval": true, 
"eval_steps": 50,
"per_device_eval_batch_size": 4,
"max_eval_samples": 25, 
"do_step_schedule_per_epoch": true,

"weight_disc": 3,
"weight_fmaps": 1,
"weight_gen": 1,
"weight_kl": 1.5,
"weight_duration": 1,
"weight_mel": 35,

"fp16": true,
"seed": 456
}
`

**Comment by atulpokharel-gp** [comment]
@C0deXG  
create a file name : preprocessor_config.json
with : 


{
  "feature_extractor_type": "VitsFeatureExtractor",
  "feature_size": 80,
  "hop_length": 256,
  "max_wav_value": 32768.0,
  "n_fft": 1024,
  "padding_side": "right",
  "padding_value": 0.0,
  "return_attention_mask": false,
  "sampling_rate": 16000
}




inside the model like like this : 
!
![Screenshot from 2024-10-28 09-22-44](https://github.com/user-attachments/assets/1a33ba3f-a68c-4db5-b69d-9c9d3a136a3a)

**Comment by C0deXG** [comment]
@atulpokharel-gp thank you so much for the reponse i solve the issue but my dataset is only 100 of one speaker so i remove all the things the refer or has speaker_Id in the config but shome-how am still getting speaker_Id error :

`Traceback (most recent call last):
  File "/content/finetune-hf-vits/run_vits_finetuning.py", line 1494, in <module>
    main()
  File "/content/finetune-hf-vits/run_vits_finetuning.py", line 1099, in main
    speaker_id=batch["speaker_id"],
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 257, in __getitem__
    return self.data[item]
KeyError: 'speaker_id'
wandb: 🚀 View run polished-cosmos-2 at: https://wandb.ai/jjhjjff4/so-custom-model-TTS/runs/4f060m6d
wandb: Find logs at: wandb/run-20241028_174011-4f060m6d/logs
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1174, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 769, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'run_vits_finetuning.py', '/content/finetune-hf-vits/training_config_examples/finetune_mms.json']' returned non-zero exit status 1.`


my config:
`{
    "project_name": "so-custom-model-TTS",
    "push_to_hub": true,
    "hub_model_id": "catsOfpeople/V5.01",
    "report_to": ["wandb"],
    "overwrite_output_dir": true,
    "output_dir": "./tmp/vits_finetuned_guj",

    "dataset_name": "khederwaaOne/s",    
    "audio_column_name": "audio", 
    "text_column_name":"transcribe",
    "train_split_name": "train",
    "eval_split_name": "train",

    "full_generation_sample_text": "Labadaas qaybood oo aanu soo sheegnay haddii la falanqeeyo mid waliba wuxuu noqonayaa bad aan xeeb lahayn iyo berri aan laga hoyan karin iyo biyo aan laga bixi karin.",
    
   "max_duration_in_seconds": 28.5,
   "min_duration_in_seconds": 2.4,

    "max_tokens_length": 500,

    "model_name_or_path": "catsOfpeople/V5.01",


    "preprocessing_num_workers": 4,

    "do_train": true,
    "num_train_epochs": 35,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "per_device_train_batch_size": 4,
    "learning_rate": 2e-5,
    "adam_beta1": 0.8,
    "adam_beta2": 0.99,
    "warmup_ratio": 0.01,
    "group_by_length": false,

    "do_eval": true, 
    "eval_steps": 50,
    "per_device_eval_batch_size": 4,
    "max_eval_samples": 25, 
    "do_step_schedule_per_epoch": true,

    "weight_disc": 3,
    "weight_fmaps": 1,
    "weight_gen": 1,
    "weight_kl": 1.5,
    "weight_duration": 1,
    "weight_mel": 35,

    "fp16": true,
    "seed": 456
}`

**Comment by C0deXG** [comment]
So i dont have speaker_ID in my dataset since i only have one speaker is there way to solve this issue @atulpokharel-gp

**Comment by atulpokharel-gp** [comment]
@C0deXG  if you do not want to modified anything in the file : "run_vits_finetuning.py"  you can just add a column name Speaker_id and assign as default value 1 . if you prefer to change in the "run_vits_finetuning.py" then you need to  modified the code  that handle the batch , and the processing part so i  suggest you to add the column in your data rather then modifing the script of @ylacombe

**Comment by C0deXG** [comment]
> @C0deXG if you do not want to modified anything in the file : "run_vits_finetuning.py" you can just add a column name Speaker_id and assign as default value 1 . if you prefer to change in the "run_vits_finetuning.py" then you need to modified the code that handle the batch , and the processing part so i suggest you to add the column in your data rather then modifing the script of @ylacombe

Do i have to add the speaker_Id into my dataset too and make it all 1?

**Comment by atulpokharel-gp** [comment]
yes !!

**Comment by C0deXG** [comment]
> yes !!

i set speaker_Id = 1 but got error:
`ValueError: Some keys are not used by the HfArgumentParser: ['Speaker_id']`

my config:
`{
    "project_name": "so-custom-model-TTS",
    "push_to_hub": true,
    "hub_model_id": "catsOfpeople/V5.01",
    "report_to": ["wandb"],
    "overwrite_output_dir": true,
    "output_dir": "./tmp/vits_finetuned_guj",
    "Speaker_d": 1,

    "dataset_name": "khederwaaOne/s",    
    "audio_column_name": "audio", 
    "text_column_name":"transcribe",
    "train_split_name": "train",
    "eval_split_name": "train",

    "full_generation_sample_text": "Labadaas qaybood oo aanu soo sheegnay haddii la falanqeeyo mid waliba wuxuu noqonayaa bad aan xeeb lahayn iyo berri aan laga hoyan karin iyo biyo aan laga bixi karin.",
    
   "max_duration_in_seconds": 28.5,
   "min_duration_in_seconds": 2.4,

    "max_tokens_length": 500,

    "model_name_or_path": "catsOfpeople/V5.01",


    "preprocessing_num_workers": 4,

    "do_train": true,
    "num_train_epochs": 35,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "per_device_train_batch_size": 4,
    "learning_rate": 2e-5,
    "adam_beta1": 0.8,
    "adam_beta2": 0.99,
    "warmup_ratio": 0.01,
    "group_by_length": false,

    "do_eval": true, 
    "eval_steps": 50,
    "per_device_eval_batch_size": 4,
    "max_eval_samples": 25, 
    "do_step_schedule_per_epoch": true,

    "weight_disc": 3,
    "weight_fmaps": 1,
    "weight_gen": 1,
    "weight_kl": 1.5,
    "weight_duration": 1,
    "weight_mel": 35,

    "fp16": true,
    "seed": 456
}`

**Comment by C0deXG** [comment]
@atulpokharel-gp 

so i did set speaker_id in config file but am still getting errror:
config:
`"project_name": "so-custom-model-TTS",
    "push_to_hub": true,
    "hub_model_id": "catsOfpeople/V5.01",
    "report_to": ["wandb"],
    "overwrite_output_dir": true,
    "output_dir": "./tmp/vits_finetuned_guj",
    "Speaker_d": 1,
    etc..`
    
    Error:
    `ValueError: Some keys are not used by the HfArgumentParser: ['Speaker_id']`

**Comment by atulpokharel-gp** [comment]
@C0deXG  can you share the dataset  structure with all the features in  it

**Comment by C0deXG** [comment]
> @C0deXG can you share the dataset structure with all the features in it

@atulpokharel-gp 
here (all the speaker_id has value of 1 sicne the speaker is one speaker):
`DatasetDict({
    train: Dataset({
        features: ['transcription', 'audio', 'speaker_id'],
        num_rows: 75
    })
})`

btw i a have qestion the reason my dataset is small is my point is to clone my voice so i made this dataset will the model have my voice or tone after the traning

**Comment by atulpokharel-gp** [comment]
> "Speaker_d": 1
@C0deXG 
can you check this in the config.json

**Comment by C0deXG** [comment]
> > "Speaker_d": 1
> > @C0deXG
> > can you check this in the config.json

@atulpokharel-gp 

my dataset has speaker_id row that has deafult value of 1 since am using one speaker dataset and also i did this in my config:
`    "dataset_name": "catsOfpeople/owoV4.000",    
    "audio_column_name": "audio", 
    "text_column_name":"transcribe",
    "train_split_name": "train",
    "eval_split_name": "train",
    "speaker_id_column_name": "speaker_id",
    "speaker_id": 1,`
    
my dataset:
`
DatasetDict({
    train: Dataset({
        features: ['audio', 'transcribe', 'speaker_id'],
        num_rows: 72
    })
})`
    
but am still getting the same error:
`ValueError: Some keys are not used by the HfArgumentParser: ['speaker_id']`

**Comment by C0deXG** [comment]
@atulpokharel-gp

**Comment by atulpokharel-gp** [comment]
@C0deXG   I suspect you just have a typo in the call you are making to the script so can you check the name in dataset  feature  and the config.json

**Comment by C0deXG** [comment]
> @C0deXG I suspect you just have a typo in the call you are making to the script so can you check the name in dataset feature and the config.json

@atulpokharel-gp 

I dont know what is wrong you can check out my dataset here `https://huggingface.co/datasets/catsOfpeople/owoV4.000`

and here is my config: 
`{
    "project_name": "so-custom-model-TTS",
    "push_to_hub": true,
    "hub_model_id": "catsOfpeople/V5.01",
    "report_to": ["wandb"],
    "overwrite_output_dir": true,
    "output_dir": "./tmp/vits_finetuned_guj",

    "dataset_name": "catsOfpeople/owoV4.000",    
    "audio_column_name": "audio", 
    "text_column_name":"transcribe",
    "train_split_name": "train",
    "eval_split_name": "train",
    "speaker_id_column_name": "speaker_id",
    "override_speaker_embeddings": true,
    "filter_on_speaker_id": 1,

    "full_generation_sample_text": "Labadaas qaybood oo aanu soo sheegnay haddii la falanqeeyo mid waliba wuxuu noqonayaa bad aan xeeb lahayn iyo berri aan laga hoyan karin iyo biyo aan laga bixi karin.",
    
   "max_duration_in_seconds": 28.5,
   "min_duration_in_seconds": 2.4,

    "max_tokens_length": 500,

    "model_name_or_path": "catsOfpeople/V5.01",


    "preprocessing_num_workers": 4,

    "do_train": true,
    "num_train_epochs": 35,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "per_device_train_batch_size": 4,
    "learning_rate": 2e-5,
    "adam_beta1": 0.8,
    "adam_beta2": 0.99,
    "warmup_ratio": 0.01,
    "group_by_length": false,

    "do_eval": true, 
    "eval_steps": 50,
    "per_device_eval_batch_size": 4,
    "max_eval_samples": 25, 
    "do_step_schedule_per_epoch": true,

    "weight_disc": 3,
    "weight_fmaps": 1,
    "weight_gen": 1,
    "weight_kl": 1.5,
    "weight_duration": 1,
    "weight_mel": 35,

    "fp16": true,
    "seed": 456
}`

and here is how am calling it in colab:
`!accelerate launch run_vits_finetuning.py /content/finetune-hf-vits/training_config_examples/finetune_mms.json`

i chnage the info in the /finetune_mms.json to my info but still getting the exact same error i try removing the speaker_id and i try to copy it from the exmaples but same issue i really dont know what to do now other then just quite :(

**Comment by C0deXG** [comment]
@atulpokharel-gp

**Comment by C0deXG** [comment]
#Issue-close
To solve the speaker_Id issue fellow this:

#42 

and also remove any mention of speaker_id or speaker in config file thanks to @atulpokharel-gp
